[package]
name = "multipart-example"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
actix-multipart.workspace = true
actix-web.workspace = true

env_logger.workspace = true
futures-util.workspace = true
log.workspace = true
sanitize-filename = "0.6"
uuid.workspace = true
