[package]
name = "cache-redis"
version = "1.0.0"
publish.workspace = true
authors = ["Jatutep Bunupuradah <bangbaew@gmail.com>"]
edition.workspace = true
rust-version.workspace = true

[dependencies]
actix-web.workspace = true
env_logger.workspace = true
redis = { workspace = true, features = ["tokio-native-tls-comp"] }
