[package]
name = "templating-minijinja"
edition.workspace = true
rust-version.workspace = true

[dependencies]
actix-web = { workspace = true }
err-report = { workspace = true }
examples-common = { workspace = true }
minijinja = { version = "2", features = ["loader"] }
minijinja-autoreload = "2"
tracing = { workspace = true }
