[package]
name = "tracing-request-id-response-header"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
actix-web.workspace = true
examples-common.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-actix-web.workspace = true
