[package]
name = "websocket-autobahn"
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "websocket-autobahn-server"
path = "src/main.rs"

[dependencies]
actix-web = { workspace = true }
actix-ws = { workspace = true }
examples-common = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
tracing = { workspace = true }
