CREATE TABLE `customer_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(100) DEFAULT '',
  `branch_name` VARCHAR(30) DEFAULT '',
  `date_added` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
