name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fmt:
    name: rustfmt check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          toolchain: stable
          components: rustfmt

      - name: rustfmt
        uses: actions-rust-lang/rustfmt@4066006ec54a31931b9b1fddfd38f2fdf2d27143 # v1.1.2

  clippy:
    name: clippy check
    runs-on: ubuntu-latest

    env:
      CI: 1
      CARGO_INCREMENTAL: false

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          toolchain: stable
          components: clippy

      - name: clippy
        timeout-minutes: 30
        run: cargo clippy --workspace --all-features --tests -- -D warnings
